/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245.project;

import static java.lang.Integer.max;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.util.Random;
import java.util.*;
import java.awt.Color;
import static jdk.nashorn.internal.objects.NativeMath.random;
import java.awt.*;

public class ColorTrap extends javax.swing.JFrame {

  Random random = new Random();
    
    public ColorTrap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        colorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colorLabel.setBackground(new java.awt.Color(255, 255, 255));
        colorLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        colorLabel.setForeground(new java.awt.Color(255, 102, 102));
        colorLabel.setText("colorLabel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(colorLabel)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorLabel)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorTrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorTrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorTrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorTrap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorTrap().setVisible(true);
             
            }
        });
        
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
       // drawCircle(g);
        setLabelName();
        setLabelColor();
    }
    
//    public void drawCircle(Graphics g)
//    {
//        nextColor(g);
//        g.fillOval(50, 50, 50, 50);
//        colorName.setForeground(Color.blue);
//    }

    public void nextCircleColor(Graphics g)
    {
        int r = random.nextInt(5);
        switch(r){
            case 0:
             g.setColor(Color.red);
             break;
            case 1:
             g.setColor(Color.yellow);
             break;
            case 2:
             g.setColor(Color.green);  
             break;
            case 3:
             g.setColor(Color.blue);  
             break;
            case 4:
             g.setColor(Color.magenta);  
             break;      
        }
    }
    public void setLabelName()
    {
        int r = random.nextInt(5);
        switch(r){
            case 0:
             colorLabel.setText("RED");
             break;
            case 1:
             colorLabel.setText("YELLOW");
             break;
            case 2:
             colorLabel.setText("GREEN"); 
             break;
            case 3:
             colorLabel.setText("BLUE"); 
             break;
            case 4:
             colorLabel.setText("MAGENTA"); 
             break;  
        }
    }
       public void setLabelColor()
    {
        int r = random.nextInt(5);
        switch(r){
            case 0:
             colorLabel.setForeground(Color.red);
             break;
            case 1:
             colorLabel.setForeground(Color.yellow);
             break;
            case 2:
             colorLabel.setForeground(Color.green);
             break;
            case 3:
             colorLabel.setForeground(Color.blue);
             break;
            case 4:
             colorLabel.setForeground(Color.magenta); 
             break;  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
